# ===============================
# = SERVER
# ===============================
server.port=8080

# ===============================
# = DATABASE
# ===============================
# TODO: get docker to work so we don't hardcode values
spring.datasource.url=jdbc:mysql://localhost:3306/bcfserver
spring.datasource.username=bcf_admin
spring.datasource.password=adminPassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# = JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=false

# ===============================
# = SECURITY: JWT & OAUTH2
# ===============================
jwt.secret=1jf93h3iod@8fjdo)(fa87967f89ac7dybfyuaioshduifobcahsudbiofasb7ud7casd76cb0sd7ybchdsasjh
jwt.expiration=86400000

spring.security.oauth2.client.registration.google.client-id=589647003834-993fomnetlehgthlb28nsdej8o529vf2.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.registration.github.client-id=your-github-client-id
spring.security.oauth2.client.registration.github.client-secret=your-github-client-secret
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/github
spring.security.oauth2.client.registration.github.scope=user:email
# ===============================
# = SECURITY: Token Blacklisting
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ===============================
# = EMAIL
# ===============================
# SMTP server details
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#TODO: replace these with BCF or OPENFAB support account
spring.mail.username=something@gmail.com
spring.mail.password=somePassword

# security
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.default-encoding=UTF-8

# ===============================
# = LOGGING
# ===============================
logging.level.org.springframework=INFO
logging.level.org.springframework.security=INFO

# ===============================
# = FLYWAY
# ===============================
#change for deployment
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration

